# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Output_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_output_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_input',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_input_text', models.TextField()),
                ('user_entered_text', models.TextField()),
                ('user_upload_text', models.TextField()),
                ('user_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
